name: pre-release

on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.ref }}

      - name: Replace toc version
        uses: Numynum/ToCVersions@v1

      - name: Package and release
        uses: BigWigsMods/packager@v2

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: scripts/tag-changelog-config.js

      - name: 'Crosspost changelog to Discord'
        uses: kludge-cs/gitcord-release-changelogger@v3.0.0
        with:
          username: 'Rick-Bot'
          avatar-url: 'https://cdn.discordapp.com/attachments/751929844920614932/934170534755860560/rick.png'
          release-name: '${{ github.event.repository.name }}: new test build has been released.'
          release-body: ${{ steps.changelog.outputs.changelog }}
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
