name: release

on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.ref }}

      - name: Replace toc version
        uses: Numynum/ToCVersions@v1

      - name: Package and release
        uses: BigWigsMods/packager@v2
